linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - testpackage

linters-settings:
  testpackage:
    skip-regexp: (export|internal)_test\.go

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
      text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*print(f|ln)?|os\\.(Un)?Setenv). is not checked"

run:
  tests: true
  build-tags:
    - integration

# Add Go version configuration
service:
  golangci-lint-version: latest
  go: "1.21" 