providers:
  google_secrets_manager:
    kind: google_secretmanager
    maps:
      - id: secrets
        path: projects/vfarcic
        keys:
          azure-openai-key: AI_KEY
          app-email-password: EMAIL_PASSWORD
          youtube-api-key: YOUTUBE_API_KEY
          youtube-token: YOUTUBE_TOKEN
          bluesky-password: BLUESKY_PASSWORD
          anthropic-api-key: ANTHROPIC_API_KEY
          github-token: GITHUB_TOKEN
          google-gemini-api-key: GOOGLE_GENERATIVE_AI_API_KEY
# Google Generative AI API key is missing. Pass it using the 'apiKey' parameter or the GOOGLE_GENERATIVE_AI_API_KEY environment variable.