{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "youtube-automation.fullname" . }}
  labels:
    {{- include "youtube-automation.labels" . | nindent 4 }}
type: Opaque
data:
  api-token: {{ .Values.apiToken | b64enc | quote }}
  {{- if .Values.git.token }}
  git-token: {{ .Values.git.token | b64enc | quote }}
  {{- end }}
{{- end }}
